const SETTINGS_DIR_NAME = '.familiar'
const SETTINGS_FILE_NAME = 'settings.json'
const FAMILIAR_BEHIND_THE_SCENES_DIR_NAME = 'familiar'
const STILLS_DIR_NAME = 'stills'
const STILLS_MARKDOWN_DIR_NAME = 'stills-markdown'
const HEARTBEATS_DIR_NAME = 'heartbeats'
const STILLS_DB_FILENAME = 'stills.db'

module.exports = {
  SETTINGS_DIR_NAME,
  SETTINGS_FILE_NAME,
  FAMILIAR_BEHIND_THE_SCENES_DIR_NAME,
  HEARTBEATS_DIR_NAME,
  STILLS_DIR_NAME,
  STILLS_MARKDOWN_DIR_NAME,
  STILLS_DB_FILENAME
}
